### ISSUE TITLE
Performance concerns

### ISSUE THREAD

**Issue by go24dev** [rinvex/cortex-tenants#43]
Hello @Omranic,

Thank for your great package. I have a concern on performance because all tenants' attached data are storing in the `tenantables` table.

Do you have any suggestion?

**Comment by Omranic** [comment]
Hello @go24dev 

Would you explain what concerns do you have in more details please.
The `tenantables` table doesn't contain the actual data, it's only the references and relations.
Would love to hear from you, and if there's any optimizations needed, feel free to send a PR :)

BTW this is a single database multi-tenancy module.

**Comment by Omranic** [comment]
This is closed due to lack of response. Feel free to re-open for discussion if needed 👍
