### ISSUE TITLE
[Proposal] Using Macroable trait.

### ISSUE THREAD

**Issue by ScSherifTarek** [rinvex/cortex-tenants#49]
Using [Macroable trait](https://laravel.com/api/5.6/Illuminate/Support/Traits/Macroable.html) will help when needs to add new methods to the tenant from other modules instead of inheriting it when we need to add a method to it.

**Comment by Omranic** [comment]
Where do you suggest to use the Macroable trait?
PRs are welcome, if you're interested please send a PR :)

**Comment by Omranic** [comment]
This is closed due to inactivity, but feel free to re-open for discussion. PRs are also welcome all the time 🙂

**Comment by ScSherifTarek** [comment]
@Omranic 
After trying to add the Macroable trait to the `Tenant` Model I got an error.

**Comment by Omranic** [comment]
What error?
